version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'db-data:/var/lib/postgres'
    ports:
      - "5432:5432"
volumes:
  db-data:
    driver: local
